// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	Book "github.com/BlazeCode1/book-grpc/app/book/model/Book"
	mock "github.com/stretchr/testify/mock"
)

// BookRepository is an autogenerated mock type for the BookRepository type
type BookRepository struct {
	mock.Mock
}

// DeleteBook provides a mock function with given fields: id
func (_m *BookRepository) DeleteBook(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBooks provides a mock function with no fields
func (_m *BookRepository) GetBooks() ([]Book.Book, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []Book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Book.Book, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Book.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Book.Book)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertBook provides a mock function with given fields: book
func (_m *BookRepository) InsertBook(book Book.Book) error {
	ret := _m.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for InsertBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(Book.Book) error); ok {
		r0 = rf(book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBook provides a mock function with given fields: id, newBookName, author
func (_m *BookRepository) UpdateBook(id string, newBookName string, author string) error {
	ret := _m.Called(id, newBookName, author)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, newBookName, author)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookRepository creates a new instance of BookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepository {
	mock := &BookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
